### ISSUE TITLE
Button not available in new TB 78.2.2

### ISSUE THREAD

**Issue by chrystalingus** [ChristophKaser/FilterButton#1]
With the update from TB 68 to 78 the Addon is still active but there are no filter buttons offered in the toolbar of a message. Any insight?
Apparently TB 78 removes the ability to customize the message toolbar (as opposed to the main toolbar). I found an addon which one user claims allows for third party addon buttons https://addons.thunderbird.net/pt-pt/thunderbird/addon/msghdr-toolbar-customize/reviews/1163120/ but so far I couldn't get it to work.

**Comment by ChristophKaser** [comment]
Duplicate (of sorts) of #2 
The new rewrite should fix this issue.
