### ISSUE TITLE
Not compatible with TB 78.3.1 

### ISSUE THREAD

**Issue by kanlukasz** [ChristophKaser/FilterButton#2]
As per title

**Comment by ChristophKaser** [comment]
I know :(
Unfortunately, the new thunderbird-extension API is not compatible with this plugin. I am not sure whether this plugin can be updated to use the new API or whether it requires functionality that is missing from the API. I will check that out when I find the time. PRs are welcome!

**Comment by tonyvsuk** [comment]
I'm really missing this plugin. I used to use it all the time (along with QuickText).

**Comment by kupietools** [comment]
This is desperately needed for newer versions. I can't believe TB doesn't do this natively.

**Comment by ChristophKaser** [comment]
I finally got around to rewriting this extension for the newest TB API. It is currently in review by mozilla, so you either have to wait a few days until it is released or install it manually :)
