### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by melissis** [ChristophKaser/FilterButton#5]
Currently, the add-on requires "[full, unrestricted access to Thunderbird, and your computer](https://support.mozilla.org/en-US/kb/permission-request-messages-thunderbird-extensions#w_have-full-unrestricted-access-to-thunderbird-and-your-computer)".
Is the new permisison-based API capable of adding toolbar buttons like a filter button, or are we required to use the old API until the new API is more complete?

**Comment by ChristophKaser** [comment]
The new API can be used to add buttons and filter button uses the new API already.
However, to evaluate filters there is no new API (yet?), and therefore the 'full, unrestricted access' permission is required.

**Comment by Cherkah** [comment]
hi, 
>  to evaluate filters there is no new API (yet?), 

is this still the case today?
